# Generated by Django 5.1.6 on 2025-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersi_app', '0002_jersi_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersi',
            name='detail',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
