# Generated by Django 5.1.6 on 2025-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersi_app', '0004_alter_jersi_category_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
