# Generated by Django 5.1.6 on 2025-05-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersi_app', '0005_alter_jersi_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateWaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=500, null=True)),
                ('store_pass', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
